openapi: 3.0.1
info:
  title: proxy_generated
  version: "1"
paths:
  /api/v1/items/6800a93d-4ba0-4c6d-a44c-f69636f6099b:
    delete:
      summary: api_v1_items_6800a93d-4ba0-4c6d-a44c-f69636f6099b_DELETE_application_json_404_application_json_1
      parameters:
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "404":
          description: api_v1_items_6800a93d-4ba0-4c6d-a44c-f69636f6099b_DELETE_application_json_404_application_json_1
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Api_V1_Items_6800a93d-4ba0-4c6d-a44c-f69636f6099b_DELETE_404_application_json_ResponseBody"
  /api/v1/items:
    post:
      summary: api_v1_items__POST_application_json_200_application_json_1
      parameters:
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Api_V1_Items_POST_application_json_RequestBody"
        required: true
      responses:
        "200":
          description: api_v1_items__POST_application_json_200_application_json_1
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Api_V1_Items_POST_200_application_json_ResponseBody"
  /api/v1/login/access-token:
    post:
      summary: api_v1_login_access-token_POST_application_x-www-form-urlencoded_200_application_json_1
      parameters:
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: api_v1_login_access-token_POST_application_x-www-form-urlencoded_200_application_json_1
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Api_V1_Login_Access-token_POST_200_application_json_ResponseBody"
  /api/v1/login/test-token:
    post:
      summary: api_v1_login_test-token_POST_application_json_200_application_json_1
      parameters:
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: api_v1_login_test-token_POST_application_json_200_application_json_1
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Api_V1_Login_Test-token_POST_200_application_json_ResponseBody"
  /api/v1/password-recovery-html-content/user3847@example.com:
    post:
      summary: api_v1_password-recovery-html-content_user3847@example.com_POST_application_json_404_application_json_1
      parameters:
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "404":
          description: api_v1_password-recovery-html-content_user3847@example.com_POST_application_json_404_application_json_1
          content:
            application/json:
              schema:
                $ref: Api_V1_Password-recovery-html-content_User3847_example.com_POST_404_application_json_ResponseBody
  /api/v1/password-recovery/user3847@example.com:
    post:
      summary: api_v1_password-recovery_user3847@example.com_POST_application_json_200_application_json_1
      parameters:
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: api_v1_password-recovery_user3847@example.com_POST_application_json_200_application_json_1
          content:
            application/json:
              schema:
                $ref: Api_V1_Password-recovery_User3847_example.com_POST_200_application_json_ResponseBody
  /api/v1/private/users:
    post:
      summary: api_v1_private_users__POST_application_json_500_text_plain_1
      parameters:
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Api_V1_Private_Users_POST_application_json_RequestBody"
        required: true
      responses:
        "500":
          description: api_v1_private_users__POST_application_json_500_text_plain_1
          content:
            text/plain:
              schema:
                type: string
  /api/v1/reset-password:
    post:
      summary: api_v1_reset-password__POST_application_json_422_application_json_1
      parameters:
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Api_V1_Reset-password_POST_application_json_RequestBody"
        required: true
      responses:
        "422":
          description: api_v1_reset-password__POST_application_json_422_application_json_1
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Api_V1_Reset-password_POST_422_application_json_ResponseBody"
  /api/v1/users/f19bfe5f-4931-46d2-b361-d65878973e59:
    delete:
      summary: api_v1_users_f19bfe5f-4931-46d2-b361-d65878973e59_DELETE_application_json_404_application_json_1
      parameters:
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "404":
          description: api_v1_users_f19bfe5f-4931-46d2-b361-d65878973e59_DELETE_application_json_404_application_json_1
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Api_V1_Users_F19bfe5f-4931-46d2-b361-d65878973e59_DELETE_404_application_json_ResponseBody"
  /api/v1/users/me:
    delete:
      summary: api_v1_users_me_DELETE_application_json_403_application_json_1
      parameters:
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "403":
          description: api_v1_users_me_DELETE_application_json_403_application_json_1
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Api_V1_Users_Me_DELETE_403_application_json_ResponseBody"
  /api/v1/users/me/password:
    patch:
      summary: api_v1_users_me_password_PATCH_application_json_422_application_json_1
      parameters:
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Api_V1_Users_Me_Password_PATCH_application_json_RequestBody"
        required: true
      responses:
        "422":
          description: api_v1_users_me_password_PATCH_application_json_422_application_json_1
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Api_V1_Users_Me_Password_PATCH_422_application_json_ResponseBody"
  /api/v1/users/signup:
    post:
      summary: api_v1_users_signup_POST_application_json_400_application_json_1
      parameters:
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Api_V1_Users_Signup_POST_application_json_RequestBody"
        required: true
      responses:
        "400":
          description: api_v1_users_signup_POST_application_json_400_application_json_1
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Api_V1_Users_Signup_POST_400_application_json_ResponseBody"
  /api/v1/users:
    post:
      summary: api_v1_users__POST_application_json_400_application_json_1
      parameters:
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Api_V1_Users_POST_application_json_RequestBody"
        required: true
      responses:
        "400":
          description: api_v1_users__POST_application_json_400_application_json_1
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Api_V1_Users_POST_400_application_json_ResponseBody"
  /api/v1/utils/health-check:
    get:
      summary: api_v1_utils_health-check__GET_200_application_json_1
      parameters:
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      responses:
        "200":
          description: api_v1_utils_health-check__GET_200_application_json_1
          content:
            application/json:
              schema:
                type: boolean
  /api/v1/utils/test-email:
    post:
      summary: api_v1_utils_test-email__POST_application_x-www-form-urlencoded_201_application_json_1
      parameters:
      - name: email_to
        in: query
        schema:
          type: string
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: string
        required: true
      responses:
        "201":
          description: api_v1_utils_test-email__POST_application_x-www-form-urlencoded_201_application_json_1
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Api_V1_Utils_Test-email_POST_201_application_json_ResponseBody"
components:
  schemas:
    Api_V1_Items_6800a93d-4ba0-4c6d-a44c-f69636f6099b_DELETE_404_application_json_ResponseBody:
      required:
      - detail
      type: object
      properties:
        detail:
          type: string
    Api_V1_Items_POST_application_json_RequestBody:
      required:
      - description
      - title
      type: object
      properties:
        title:
          type: string
        description:
          type: string
    Api_V1_Items_POST_200_application_json_ResponseBody:
      required:
      - created_at
      - description
      - id
      - owner_id
      - title
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        id:
          type: string
        owner_id:
          type: string
        created_at:
          type: string
    Api_V1_Login_Access-token_POST_200_application_json_ResponseBody:
      required:
      - access_token
      - token_type
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
    Api_V1_Login_Test-token_POST_200_application_json_ResponseBody:
      required:
      - created_at
      - email
      - full_name
      - id
      - is_active
      - is_superuser
      type: object
      properties:
        email:
          type: string
        is_active:
          type: boolean
        is_superuser:
          type: boolean
        full_name:
          nullable: true
        id:
          type: string
        created_at:
          type: string
    Api_V1_Password-recovery-html-content_User3847_example.com_POST_404_application_json_ResponseBody:
      required:
      - detail
      type: object
      properties:
        detail:
          type: string
    Api_V1_Password-recovery_User3847_example.com_POST_200_application_json_ResponseBody:
      required:
      - message
      type: object
      properties:
        message:
          type: string
    Api_V1_Private_Users_POST_application_json_RequestBody:
      required:
      - email
      - full_name
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        full_name:
          type: string
    Input:
      type: object
      properties: {}
    Detail:
      required:
      - input
      - loc
      - msg
      - type
      type: object
      properties:
        type:
          type: string
        loc:
          type: array
          items:
            type: string
        msg:
          type: string
        input:
          $ref: "#/components/schemas/Input"
    Api_V1_Reset-password_POST_application_json_RequestBody:
      type: object
      properties: {}
    Api_V1_Reset-password_POST_422_application_json_ResponseBody:
      required:
      - detail
      type: object
      properties:
        detail:
          type: array
          items:
            $ref: "#/components/schemas/Detail"
    Api_V1_Users_F19bfe5f-4931-46d2-b361-d65878973e59_DELETE_404_application_json_ResponseBody:
      required:
      - detail
      type: object
      properties:
        detail:
          type: string
    Api_V1_Users_Me_DELETE_403_application_json_ResponseBody:
      required:
      - detail
      type: object
      properties:
        detail:
          type: string
    Api_V1_Users_Me_Password_PATCH_application_json_RequestBody:
      type: object
      properties: {}
    Api_V1_Users_Me_Password_PATCH_422_application_json_ResponseBody:
      required:
      - detail
      type: object
      properties:
        detail:
          type: array
          items:
            $ref: "#/components/schemas/Detail"
    Api_V1_Users_Signup_POST_application_json_RequestBody:
      required:
      - email
      - full_name
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        full_name:
          type: string
    Api_V1_Users_Signup_POST_400_application_json_ResponseBody:
      required:
      - detail
      type: object
      properties:
        detail:
          type: string
    Api_V1_Users_POST_application_json_RequestBody:
      required:
      - email
      - full_name
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        full_name:
          type: string
    Api_V1_Users_POST_400_application_json_ResponseBody:
      required:
      - detail
      type: object
      properties:
        detail:
          type: string
    Api_V1_Utils_Test-email_POST_201_application_json_ResponseBody:
      required:
      - message
      type: object
      properties:
        message:
          type: string
